//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMaster.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Book
    {
        public Book()
        {
            this.BookAuthor = new HashSet<BookAuthor>();
            this.BookSubject = new HashSet<BookSubject>();
            this.BookSubject1 = new HashSet<BookSubject>();
            this.Circulation = new HashSet<Circulation>();
            this.Cover1 = new HashSet<Cover>();
        }
    
        public string Id { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public System.DateTime FirstPublishDate { get; set; }
        public string Description { get; set; }
        public string Cover { get; set; }
        public string Authors
        {
            get
            {
                return "by " + string.Join(", ", BookAuthor.Select(bookAuthor => bookAuthor.Author.Fullname));
            }
        }

        public string Subjects
        {
            get
            {
                return string.Join(", ", BookSubject.Select(bookSubject => bookSubject.Subject.SubjectName));
            }
        }
    
        public virtual ICollection<BookAuthor> BookAuthor { get; set; }
        public virtual ICollection<BookSubject> BookSubject { get; set; }
        public virtual ICollection<BookSubject> BookSubject1 { get; set; }
        public virtual ICollection<Circulation> Circulation { get; set; }
        public virtual ICollection<Cover> Cover1 { get; set; }
    }
}
