//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMaster.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Circulation
    {
        public int Id { get; set; }
        public string IdCustomer { get; set; }
        public string IdBook { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public System.DateTime DateOfReturn { get; set; }
        public System.DateTime ReturnUntil { get; set; }
        public Nullable<int> IdEmployee { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
