//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMaster.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Circulation = new HashSet<Circulation>();
        }
    
        public string Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Adress { get; set; }
        public int IdCity { get; set; }
        public string NumberPhone { get; set; }
        public string Email { get; set; }
        public string Zip { get; set; }
    
        public virtual ICollection<Circulation> Circulation { get; set; }
        public virtual City City { get; set; }
    }
}
